Add missing <sstream> header include
This is needed to fix the below errors on some compilers:

Initialize.cpp:4476:27: error: implicit instantiation of
undefined template 'std::basic_stringstream'
std::stringstream cooperativeMatrixFuncs;