Fix a compile error on VS2013 when including from a project that includes windows.h and does not define NOMINMAX (http://stackoverflow.com/questions/2789481/problem-calling-stdmax)
1>h:\dev\source2\main\src\thirdparty\glslang\glslang\include\intermediate.h(908): error C2589: '(' : illegal token on right side of '::' (vulkan\renderdevicevulkan.cpp)
1>h:\dev\source2\main\src\thirdparty\glslang\glslang\include\intermediate.h(908): error C2059: syntax error : '::' (vulkan\renderdevicevulkan.cpp)